### ISSUE TITLE
安卓系统6.0拍照后不能在界面显示出来

### ISSUE THREAD

**Issue by weilixing00** [xuehuayous/Android-ImageCrop#1]
测试手机  华为 6.0系统  拍照后ImageView不能显示图片
05-16 15:33:16.418 6746-6746/com.kevin.imagecrop E/TransformImageView: onFailure: setImageUri
                                                                       java.io.FileNotFoundException: Permission denied
                                                                           at android.os.Parcel.openFileDescriptor(Native Method)
                                                                           at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:270)
                                                                           at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:200)
                                                                           at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:948)
                                                                           at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:806)
                                                                           at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:760)
                                                                           at com.kevin.crop.util.BitmapLoadUtils$BitmapWorkerTask.doInBackground(BitmapLoadUtils.java:88)
                                                                           at com.kevin.crop.util.BitmapLoadUtils$BitmapWorkerTask.doInBackground(BitmapLoadUtils.java:60)
                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:307)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                           at java.lang.Thread.run(Thread.java:833)

**Comment by WenkaiZhou** [comment]
是由于Android 6.0权限认证的问题造成的，已经添加权限申请
